---
  - name: master playbook
    hosts: slave1
    become: yes
    become_user: root

    handlers: 
      - name: Restart server
        command: 
          args: reboot now

    tasks:
      - name: Install epel packages
        yum: 
          name: epel-release
          state: latest
      
      - name: Install docker and some dependencies
        yum: 
          name: python3-pip, docker
          state: present

      - name: Start docker service
        service:
          name: docker
          state: started
          enabled: yes

      - name: Create docker group
        group:
          name: docker
          state: present

      - name: Useradd centos to Docker group
        user:
          name: centos
          group: docker
        notify: 
          - Restart Server
      
      - name: Start a Docker container
        docker_container:
          name: nginx1
          image: abhishek4cloud/nginx1
          state: started
          ports:
            # publish container port 80 as host port 8080
            - "8080:80"
     
      - name: Start a docker container
        docker_container:
          name: nginx2
          image: abhishek4cloud/nginx2
          state: started
          ports:
            # Publish container port 80 as host port 8085
            - "8085:80"
